name: Bazel

on:
   pull_request: {}
   push: {}

jobs:
  build_and_test_ubuntu24:
    name: Linux Ubuntu 24.04 build <GCC 9.4.0>
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Build
      run: |
        cd tests
        bazel build //...
